// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34011
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TaxCalculator.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Tax Calculation (Gherkin)", new string[] {
            "gherkin"}, SourceFile="TaxCalculation_Gherkin.feature", SourceLine=1)]
    public partial class TaxCalculationGherkinFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "TaxCalculation_Gherkin.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Tax Calculation (Gherkin)", "", ProgrammingLanguage.CSharp, new string[] {
                        "gherkin"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Emplyee without children", SourceLine=3)]
        public virtual void EmplyeeWithoutChildren()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Emplyee without children", ((string[])(null)));
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given("the monthly gross salary of the employee is 200000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.And("there are no children in the family", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.When("the tax is calculated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
 testRunner.Then("the monthly net salary of the employee should be 131000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void EmplyeeWithoutChildrenSO(string gross, string net, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Emplyee without children (SO)", exampleTags);
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given(string.Format("the monthly gross salary of the employee is {0}", gross), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
 testRunner.And("there are no children in the family", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.When("the tax is calculated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.Then(string.Format("the monthly net salary of the employee should be {0}", net), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Emplyee without children (SO), 100000", SourceLine=18)]
        public virtual void EmplyeeWithoutChildrenSO_100000()
        {
            this.EmplyeeWithoutChildrenSO("100000", "65500", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Emplyee without children (SO), 200000", SourceLine=19)]
        public virtual void EmplyeeWithoutChildrenSO_200000()
        {
            this.EmplyeeWithoutChildrenSO("200000", "131000", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Emplyee without children (SO), 300000", SourceLine=20)]
        public virtual void EmplyeeWithoutChildrenSO_300000()
        {
            this.EmplyeeWithoutChildrenSO("300000", "196500", ((string[])(null)));
        }
        
        public virtual void EmployeeWoChildren_Details(string gross, string net, string contributions, string incomeTax, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Employee wo children - details", exampleTags);
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given(string.Format("the monthly gross salary of the employee is {0}", gross), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 25
 testRunner.And("there are no children in the family", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.When("the tax is calculated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
 testRunner.Then(string.Format("the monthly net salary of the employee should be {0}", net), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Social Security Contributions",
                        "Income Tax"});
            table1.AddRow(new string[] {
                        string.Format("{0}", contributions),
                        string.Format("{0}", incomeTax)});
#line 28
 testRunner.And("the following taxes are paid by the employee", ((string)(null)), table1, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Employee wo children - details, 100000", SourceLine=33)]
        public virtual void EmployeeWoChildren_Details_100000()
        {
            this.EmployeeWoChildren_Details("100000", "65500", "18000", "16000", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Employee wo children - details, 200000", SourceLine=34)]
        public virtual void EmployeeWoChildren_Details_200000()
        {
            this.EmployeeWoChildren_Details("200000", "131000", "37000", "32000", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Employee wo children - details, 300000", SourceLine=35)]
        public virtual void EmployeeWoChildren_Details_300000()
        {
            this.EmployeeWoChildren_Details("300000", "196500", "55500", "48000", ((string[])(null)));
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
