# ------------------------------------------------------------------------------
#  <auto-generated>
#      This code was generated by SpecRun.Excel (http://www.specrun.com/Excel).
#      SpecFlow Version:1.9.0.77
#      SpecRun.Excel Version:1.1.0.0
# 
#      Changes to this file may cause incorrect behavior and will be lost if
#      the code is regenerated.
#  </auto-generated>
# ------------------------------------------------------------------------------

@excel-gherkin 
Feature: Tax Calculation (Excel Feature)

Scenario: Emplyee without children
	Given the monthly gross salary of the employee is 200000
	And there are no children in the family
	When the tax is calculated
	Then the monthly net salary of the employee should be 131000
	And the following taxes are paid by the employee
		| Social Security Contributions | Income Tax |
		| 37000                         | 32000      |


Scenario Outline: Emplyee without children (SO)
	Given the monthly gross salary of the employee is <gross>
	And there are no children in the family
	When the tax is calculated
	Then the monthly net salary of the employee should be <net>

Examples: 
	| gross  | net    |
	| 100000 | 65500  |
	| 200000 | 131000 |
	| 300000 | 196500 |


Scenario Outline: Emplyee with children
	Given the monthly gross salary of the employee is <gross>
	And there are <children> children in the family
	When the tax is calculated
	Then the monthly net salary of the employee should be <net>

Examples: 
	| gross  | children | net    |
	| 100000 | 1        | 75500  |
	| 100000 | 2        | 81500  |
	| 200000 | 2        | 151000 |
	| 200000 | 3        | 163000 |
	| 800000 | 3        | 623000 |


